### ISSUE TITLE
Event tracking

### ISSUE THREAD

**Issue by tobozo** [hpwit/SID6581#1]
please add capability to fire user callbacks from specific events, so a user implementing one of your examples can customize as such:

```C
enum sidEvent {
  SID_NEW_TRACK,
  SID_START_PLAY,
  SID_END_PLAY
};

void myCallback(  sidEvent event ) {
  switch( event ) {
   case SID_NEW_TRACK: 
     Serial.printf( "New track: %s\n", sid.getFilename() );
   break;
   case SID_START_PLAY: 
     Serial.printf( "Start play: %s\n", sid.getFilename() );
   break;
   case SID_END_PLAY:
     Serial.println("End of track");
   break;
  }
}
```

... and add it from the `setup()` by doing something like this :

```C
sid.onEvent = &myCallback;
```

the performance curlpit can be avoided by doing so in a non-blockable fashion (ex: throwing the callback in another task queue on the *other* core or using a time budget)

**Comment by hpwit** [comment]
done
