### ISSUE TITLE
PSID tunes mute or only one note.

### ISSUE THREAD

**Issue by XadNightfall** [hpwit/SID6581#16]
Yep, i'm a bug hunter :-)

These PSID tunes don't play or play only one note.

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Treasure_is_All_Mine.sid
https://hvsc.csdb.dk/MUSICIANS/S/Schneider_Markus/VandaliSID.sid
http://csdb.dk/getinternalfile.php/210968/lastnightcjw.sid

in this case "Undocumented / IIlegal 6510 Opcodes" are not used.

I have personally disassembled the SID code, it seems a problem of stack pointer of the CPU emu (probably)

Obviously these sids are played regularly with all sidplayers.

thanks.

**Comment by tobozo** [comment]
hey @XadNightfall thanks for your feedback, 

I'll move the discussion to your initial post (#15) and provide a reply
