### ISSUE TITLE
Unified API

### ISSUE THREAD

**Issue by tobozo** [hpwit/SID6581#3]
methods naming differ between cpu and sid objects, also having to choose between one or another excludes the possibility to use both in the same sketch (unless complicated code)

suggestions:

- "cpu" as object name -> could be renamed to *sidFile*
- "sid" as object name -> could be renamed to *sidData* 
- using a single api for both sidFile and sidDate is possible with a class helper sidAbstractFile, then all methods except *SIDFile() can be virtual/shared from the user point of view

**Comment by hpwit** [comment]
Yes indeed I will:
export all the function related to playing the registry dump (sidData ) in a new class
and let the sidcore function in another class
so we will have 4 classes
SID (the core Sid function (set et get registers and other funky stuff)
SidFile (to play the native .sid files)
SidData (to play the registry dump)
SIDKeyboard( to use the Sid as a synth)

**Comment by hpwit** [comment]
done
