### ISSUE TITLE
getWaveform() returns more than expected

### ISSUE THREAD

**Issue by tobozo** [hpwit/SID6581#4]
![image](https://user-images.githubusercontent.com/1893754/78041103-9f0a3880-7370-11ea-8f1d-3370da12d17b.png)

it's missing `#define SID_WAVEFORM_SILENCE 0`

**Comment by hpwit** [comment]
do you just want to add a new more wave form?
or the function returns something other than 0,16,32,64,128 ?

**Comment by tobozo** [comment]
the function returns 0 when no song has been played yet

**Comment by hpwit** [comment]
yes cause when the Sid is reset all value are 0 by default in the registries

**Comment by tobozo** [comment]
the documentation is incomplete and needs an update anyway

![image](https://user-images.githubusercontent.com/1893754/78133966-a76d7c80-741f-11ea-8733-ec04f417e0cc.png)


also for the sakes of semantics `SID_WAVEFORM_PULSE` should be named `SID_WAVEFORM_SQUARE`

**Comment by hpwit** [comment]
defined 
#define SID_WAVEFORM_TRIANGLE (1<<4)
#define SID_WAVEFORM_SAWTOOTH (1<<5)
#define SID_WAVEFORM_SQUARE (1<<6)
#define SID_WAVEFORM_NOISE (1<<7)
#define SID_WAVEFORM_SILENCE 0
