### ISSUE TITLE
loop controls ?

### ISSUE THREAD

**Issue by tobozo** [hpwit/SID6581#8]
if loop controls don't exist, this could be a way to implement them:

```C

enum Loopmode {
  MODE_LOOP_OFF, // don't loop (default, will play next until end of sid and/or track)
  MODE_LOOP_SID,  // loop all songs available in one sid
  MODE_LOOP_TRACK // loop all tracks available in one playlist
};

player->setLoopmode( Loopmode mode );

```

**Comment by hpwit** [comment]
I agree. But as the the .sid files I need to see how to know the end of the track or I will have to make it play for a certain number of time.

**Comment by tobozo** [comment]
the standard length is 180 seconds on the java utility

**Comment by hpwit** [comment]
I think I can just make it configurable. 
When doing a play it will play for a specific duration before going to the next one.

**Comment by hpwit** [comment]
done
   MODE_SINGLE_TRACK, // don't loop (default, will play next until end of sid and/or track)
    MODE_SINGLE_SID,// play all songs available in one sid once
    MODE_LOOP_SID, //loop all songs in on sid file
    MODE_LOOP_PLAYLIST_SINGLE_TRACK, // loop all tracks available in one playlist playing the default tunes
    MODE_LOOP_PLAYLIST_SINGLE_SID //loop all tracks available in one playlist playing all the subtunes
